package:
  name: samuroi
  version: "0.1"

source:
  git_url: https://github.com/samuroi/SamuROI.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - matplotlib
    - pillow
    - opencv
    - h5py
    - scikit-image
    - pyqt

test:
  imports:
    - samuroi

about:
  home: https://github.com/samuroi/SamuROI
  license: MIT
  license_file: LICENSE